package ar.uba.dc.rfm.minisat;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ClauseInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ClauseInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ClauseInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minisatJNI.delete_ClauseInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getLBD() {
    return minisatJNI.ClauseInfo_getLBD(swigCPtr, this);
  }

  public double getActivity() {
    return minisatJNI.ClauseInfo_getActivity(swigCPtr, this);
  }

  public intseq getLiterals() {
    return new intseq(minisatJNI.ClauseInfo_getLiterals(swigCPtr, this), false);
  }

  public ClauseInfo() {
    this(minisatJNI.new_ClauseInfo(), true);
  }

}
