package ar.uba.dc.rfm.minisat;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class clauseseq {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public clauseseq(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(clauseseq obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minisatJNI.delete_clauseseq(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public clauseseq() {
    this(minisatJNI.new_clauseseq__SWIG_0(), true);
  }

  public clauseseq(long n) {
    this(minisatJNI.new_clauseseq__SWIG_1(n), true);
  }

  public long size() {
    return minisatJNI.clauseseq_size(swigCPtr, this);
  }

  public long capacity() {
    return minisatJNI.clauseseq_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    minisatJNI.clauseseq_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return minisatJNI.clauseseq_isEmpty(swigCPtr, this);
  }

  public void clear() {
    minisatJNI.clauseseq_clear(swigCPtr, this);
  }

  public void add(ClauseInfo x) {
    minisatJNI.clauseseq_add(swigCPtr, this, ClauseInfo.getCPtr(x), x);
  }

  public ClauseInfo get(int i) {
    return new ClauseInfo(minisatJNI.clauseseq_get(swigCPtr, this, i), false);
  }

  public void set(int i, ClauseInfo val) {
    minisatJNI.clauseseq_set(swigCPtr, this, i, ClauseInfo.getCPtr(val), val);
  }

}
