ALTER TABLE EXPERIMENTS ADD COLUMN IF NOT EXISTS "keep_learnts_limit" boolean NOT NULL DEFAULT false;
ALTER TABLE EXPERIMENTS ADD COLUMN IF NOT EXISTS "keep_restarts" boolean NOT NULL DEFAULT false;
ALTER TABLE EXPERIMENTS ADD COLUMN IF NOT EXISTS "keep_learnt_facts" boolean NOT NULL DEFAULT false;