/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class intseq {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public intseq(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(intseq obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minisatJNI.delete_intseq(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public intseq() {
    this(minisatJNI.new_intseq__SWIG_0(), true);
  }

  public intseq(long n) {
    this(minisatJNI.new_intseq__SWIG_1(n), true);
  }

  public long size() {
    return minisatJNI.intseq_size(swigCPtr, this);
  }

  public long capacity() {
    return minisatJNI.intseq_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    minisatJNI.intseq_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return minisatJNI.intseq_isEmpty(swigCPtr, this);
  }

  public void clear() {
    minisatJNI.intseq_clear(swigCPtr, this);
  }

  public void add(int x) {
    minisatJNI.intseq_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return minisatJNI.intseq_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    minisatJNI.intseq_set(swigCPtr, this, i, val);
  }

}
